import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "@/Auth/AuthProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className="min-h-screen bg-gray-100">
          {/* Your navbar and other components */}
          <Navbar/>
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
